spring.application.name=payments-api
# Configuração da Conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/payments_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuração temporária do Flyway (Vamos desativar só para testar o arranque)
spring.flyway.enabled=true

# Configurações de Teste (Sandbox) do M-Pesa
mpesa.api.key=ChaveFornecidaPeloMpesa
mpesa.public.key=ChavePublicaParaGerarOToken
mpesa.service.code=CodigoDeServicoEx12345
mpesa.initiator.identifier=IdentificadorDoIniciador